export interface PartnerInterface {
  id: number ;
  name: string;
  firstname: string;
  lastname: string;
  lastname2: string;
  email: string;
  mobile: string;
  phone: string;
  documentCountryId: number;
  documentType: number;
  documentNumber: string;
  documentSupportNumber: string;
  gender: string;
  birthdate: Date | null;
  age:number;
  residenceStreet: string;
  residenceStreet2: string;
  residenceZip: string;
  residenceCity: string;
  residenceStateId:number;
  residenceCountryId: number;
  street:string;
  street2: string;
  zip: string;
  city: string
  stateId:number;
  countryId: number;
  nationality: number;
  isAgency: boolean;
  isCompany:boolean;
  tagIds: number[];
  lastStay: string;
  vatNumber: string;
  vatDocumentType: string;
  comment:string;
  language:string;
  userId: number;
  paymentTerms: number;
  pricelistId: number;
  salesReference: string;
  saleChannelId: number;
  commission:number;
  invoicingPolicy:string;
  daysAutoInvoice: number;
  invoicingMonthDay: number;
  invoiceToAgency: string;
}
